---
# handlers file for freeradius

- name: restart smbd
  service:
    name: smbd
    state: restarted
  listen: "restart samba"

- name: restart nmbd
  service:
    name: nmbd
    state: restarted
  listen: "restart samba"

- name: restart sssd
  service:
    name: sssd
    state: restarted

- name: restart chrony
  service:
    name: chrony
    state: restarted

- name: restart freeradius
  become: true
  service:
    name: freeradius
    state: restarted
