---

- block:

  - name: Ensure the override directory exists (systemd)
    file:
      name: "/etc/systemd/system/{{ pdns_rec_service_name }}.service.d"
      state: directory
      owner: root
      group: root

  - name: Override the PowerDNS Recursor unit (systemd)
    template:
      src: "override-service.systemd.conf.j2"
      dest: "/etc/systemd/system/{{ pdns_rec_service_name }}.service.d/override.conf"
      owner: root
      group: root
    notify: reload systemd and restart PowerDNS Recursor

  when: pdns_rec_service_overrides != {}
    and ansible_service_mgr == "systemd"

- name: Ensure that the PowerDNS Recursor configuration directory exists
  file:
    name: "{{ pdns_rec_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Generate the PowerDNS Recursor configuration
  template:
    src: recursor.conf.j2
    dest: "{{ pdns_rec_config_dir }}/{{ pdns_rec_config_file }}"
    owner: "root"
    group: "{{ pdns_rec_group }}"
    mode: 0640
  notify: restart PowerDNS Recursor

- name: Ensure that the PowerDNS Recursor 'include-dir' directory exists
  file:
    name: "{{ pdns_rec_config['include-dir'] }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  when: "pdns_rec_config['include-dir'] is defined"

- name: Generate the PowerDNS Recursor Lua config-file
  copy:
    dest: "{{ pdns_rec_config_lua }}"
    content: "{{ pdns_rec_config_lua_file_content }}"
    owner: "root"
    group: "{{ pdns_rec_group }}"
    mode: 0640
  notify: restart PowerDNS Recursor
  when: pdns_rec_config_lua_file_content != ""

- name: Generate PowerDNS Recursor Lua dns-script
  copy:
    dest: "{{ pdns_rec_config_dns_script }}"
    content: "{{ pdns_rec_config_dns_script_file_content }}"
    owner: "root"
    group: "{{ pdns_rec_group }}"
    mode: 0640
  notify: restart PowerDNS Recursor
  when: pdns_rec_config_dns_script_file_content != ""

- name: Insert forward-zones
  copy:
    dest: "/etc/rsyslog.d/40-cyberland.conf"
    src: "{{ role_path }}/files/40-cyberland.conf"
    owner: "root"
    group: "{{ pdns_rec_group }}"
    mode: 0644
  notify: restart PowerDNS Recursor

- name: Insert logrotate
  lineinfile:
    path: "/etc/logrotate.d/rsyslog"
    line: "\n/var/log/pdns-recursor/recursor.info\n/var/log/pdns-recursor/recursor.warn\n/var/log/pdns-recursor/recursor.err"
    insertafter: "/var/log/messages"

- name: Insert rsyslog
  copy:
    dest: "/etc/rsyslog.d/40-cyberland.conf"
    src: "{{ role_path }}/files/40-cyberland.conf"
    owner: "root"
    group: "{{ pdns_rec_group }}"
    mode: 0644
  notify: restart rsyslog


